language: node_js
node_js:
  - "4.4"
  - "6.1"
services:
  - mongodb
  - redis-server
before_install:
  - npm install -g pm2
before_script:
  - sleep 20
after_failure: "cat /home/travis/build/stefanogianelli/camus-server/npm-debug.log"
